---
- name: Configure Web Servers
  hosts: web_server
  become: true
  roles:
    - httpd_role

- name: Install Ansible
  hosts: jenkins_server
  become: true
  roles:
    - jenkins_role

- name: Nexus Repository Setup
  hosts: nexus_server
  become: true
  roles: 
    - nexus_role