---
# handlers file for nexus_role
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Nexus service
  ansible.builtin.systemd:
    name: nexus
    state: restarted
    enabled: yes